// AUTO-GENERATED by scripts/generateDataset.mjs — do not edit by hand.
import type { MenuItem } from "../types/restaurant";

export type MenuBankItem = [name: string, description: string, price: number, category: string, vegType: "veg" | "non-veg" | "vegan"];

export const MENU_BANKS: Record<string, MenuBankItem[]> = {
  "South Indian": [
    [
      "Masala Dosa",
      "Crispy golden dosa filled with spiced potato masala",
      110,
      "Tiffins",
      "veg"
    ],
    [
      "Ghee Roast Dosa",
      "Buttery dosa roasted to a deep golden crisp",
      140,
      "Tiffins",
      "veg"
    ],
    [
      "Mysore Masala Dosa",
      "Spicy red chutney spread with potato masala",
      150,
      "Tiffins",
      "veg"
    ],
    [
      "Idli Sambar",
      "Steamed rice cakes with lentil sambar and chutney",
      90,
      "Tiffins",
      "veg"
    ],
    [
      "Medu Vada",
      "Crispy lentil doughnuts with sambar",
      100,
      "Tiffins",
      "veg"
    ],
    [
      "Pongal",
      "Savory rice-lentil porridge with ghee tempering",
      120,
      "Tiffins",
      "veg"
    ],
    [
      "Rava Upma",
      "Creamy semolina with mustard, curry leaf and cashews",
      110,
      "Tiffins",
      "veg"
    ],
    [
      "Poori Bhaji",
      "Fluffy pooris with potato bhaji and chutney",
      130,
      "Tiffins",
      "veg"
    ],
    [
      "Filter Coffee",
      "Frothy South Indian filter coffee",
      40,
      "Beverages",
      "veg"
    ],
    [
      "Sweet Lassi",
      "Thick creamy yogurt drink",
      100,
      "Beverages",
      "veg"
    ],
    [
      "Curd Rice",
      "Cool yogurt rice with pomegranate",
      140,
      "Main Course",
      "veg"
    ],
    [
      "Sambar Rice",
      "Steamed rice mixed with spicy sambar",
      160,
      "Main Course",
      "veg"
    ]
  ],
  "Chettinad": [
    [
      "Chettinad Chicken",
      "Fiery Chettinad chicken curry with robust masala",
      320,
      "Main Course",
      "non-veg"
    ],
    [
      "Chettinad Mutton Sukka",
      "Dry roasted mutton with coconut and fennel",
      380,
      "Main Course",
      "non-veg"
    ],
    [
      "Kuzhi Paniyaram",
      "Crisp dumplings in tangy sauce",
      180,
      "Starters",
      "veg"
    ],
    [
      "Prawn Chettinad",
      "Prawns simmered in freshly ground masala",
      420,
      "Main Course",
      "non-veg"
    ],
    [
      "Chicken 65",
      "Crispy deep-fried chicken with curry leaf tempering",
      260,
      "Starters",
      "non-veg"
    ],
    [
      "Seeraga Samba Biryani",
      "Fragrant short-grain rice dum biryani",
      340,
      "Biryani",
      "non-veg"
    ],
    [
      "Vepudu Platter",
      "Mixed vegetable saute with curry leaves",
      200,
      "Main Course",
      "veg"
    ],
    [
      "Aappam with Vegetable Stew",
      "Lacy fermented rice pancakes",
      220,
      "Main Course",
      "veg"
    ],
    [
      "Lemon Rice",
      "Turmeric rice with lemon and peanuts",
      130,
      "Main Course",
      "veg"
    ]
  ],
  "Biryani": [
    [
      "Hyderabadi Chicken Biryani",
      "Basmati layered with spiced chicken, dum cooked",
      340,
      "Biryani",
      "non-veg"
    ],
    [
      "Mutton Dum Biryani",
      "Tender mutton slow-cooked under sealed dough",
      420,
      "Biryani",
      "non-veg"
    ],
    [
      "Veg Dum Biryani",
      "Seasonal vegetables layered with fragrant rice",
      250,
      "Biryani",
      "veg"
    ],
    [
      "Egg Biryani",
      "Masala eggs over jeera rice",
      230,
      "Biryani",
      "non-veg"
    ],
    [
      "Chicken 65",
      "Fiery fried chicken starter",
      260,
      "Starters",
      "non-veg"
    ],
    [
      "Mirchi Ka Salan",
      "Tangy peanut-chilli gravy for biryani",
      90,
      "Side",
      "veg"
    ],
    [
      "Raita",
      "Cool yogurt with cucumber and mint",
      70,
      "Side",
      "veg"
    ],
    [
      "Double Ka Meetha",
      "Indian bread pudding with saffron",
      140,
      "Desserts",
      "veg"
    ],
    [
      "Gulab Jamun",
      "Warm milk dumplings in sugar syrup",
      110,
      "Desserts",
      "veg"
    ],
    [
      "Iranian Chai",
      "Milk tea brewed with cardamom",
      60,
      "Beverages",
      "veg"
    ]
  ],
  "North Indian": [
    [
      "Butter Chicken",
      "Tandoori chicken in a rich, creamy tomato gravy",
      340,
      "Main Course",
      "non-veg"
    ],
    [
      "Paneer Butter Masala",
      "Soft paneer cubes in a silky tomato-butter gravy",
      280,
      "Main Course",
      "veg"
    ],
    [
      "Dal Makhani",
      "Black lentils simmered overnight with butter",
      250,
      "Main Course",
      "veg"
    ],
    [
      "Palak Paneer",
      "Creamy spinach with cottage cheese",
      270,
      "Main Course",
      "veg"
    ],
    [
      "Chole Bhature",
      "Punjabi chickpeas with fluffy fried bread",
      220,
      "Main Course",
      "veg"
    ],
    [
      "Kadhai Chicken",
      "Wok-tossed chicken with peppers and onions",
      330,
      "Main Course",
      "non-veg"
    ],
    [
      "Tandoori Chicken",
      "Smoky clay-oven roasted chicken",
      320,
      "Starters",
      "non-veg"
    ],
    [
      "Paneer Tikka",
      "Chargrilled cottage cheese in spiced yogurt",
      260,
      "Starters",
      "veg"
    ],
    [
      "Garlic Naan",
      "Leavened bread with garlic and butter",
      70,
      "Breads",
      "veg"
    ],
    [
      "Butter Naan",
      "Soft pull-apart naan brushed with butter",
      60,
      "Breads",
      "veg"
    ],
    [
      "Roti",
      "Whole wheat flatbread from the tandoor",
      30,
      "Breads",
      "veg"
    ],
    [
      "Shahi Paneer",
      "Rich cashew-cream gravy with paneer",
      290,
      "Main Course",
      "veg"
    ],
    [
      "Chicken Tikka",
      "Yogurt-marinated chargrilled chicken",
      310,
      "Starters",
      "non-veg"
    ],
    [
      "Matar Paneer",
      "Green peas with paneer in onion-tomato gravy",
      260,
      "Main Course",
      "veg"
    ],
    [
      "Kulfi Falooda",
      "Creamy kulfi with vermicelli and rose syrup",
      150,
      "Desserts",
      "veg"
    ],
    [
      "Gajar Ka Halwa",
      "Slow-cooked carrot pudding with ghee",
      160,
      "Desserts",
      "veg"
    ]
  ],
  "Mughlai": [
    [
      "Mutton Rogan Josh",
      "Slow-braised mutton in a rich Kashmiri gravy",
      420,
      "Main Course",
      "non-veg"
    ],
    [
      "Chicken Korma",
      "Creamy almond-posy curry",
      320,
      "Main Course",
      "non-veg"
    ],
    [
      "Nihari with Naan",
      "Overnight slow-cooked meat stew",
      380,
      "Main Course",
      "non-veg"
    ],
    [
      "Seekh Kebab",
      "Minced meat skewers with mint chutney",
      300,
      "Starters",
      "non-veg"
    ],
    [
      "Sheermal",
      "Sweet saffron milk bread",
      90,
      "Breads",
      "veg"
    ],
    [
      "Lucknowi Biryani",
      "Awadhi style fragrant biryani",
      360,
      "Biryani",
      "non-veg"
    ],
    [
      "Shahi Tukda",
      "Bread slices in saffron rabri",
      150,
      "Desserts",
      "veg"
    ],
    [
      "Sheer Khurma",
      "Saffron milk with dates and nuts",
      130,
      "Desserts",
      "veg"
    ]
  ],
  "Chinese": [
    [
      "Chilli Chicken",
      "Crispy chicken tossed in fiery soy-garlic sauce",
      300,
      "Starters",
      "non-veg"
    ],
    [
      "Veg Manchurian",
      "Crisp veggie balls in soy-garlic glaze",
      240,
      "Starters",
      "veg"
    ],
    [
      "Chilli Paneer",
      "Bell peppers and soft paneer in hot sauce",
      280,
      "Starters",
      "veg"
    ],
    [
      "Hakka Noodles",
      "Smoky wok-fried noodles with julienned veggies",
      260,
      "Noodles",
      "veg"
    ],
    [
      "Chicken Fried Rice",
      "Wok-fried rice with chicken and scallions",
      280,
      "Rice",
      "non-veg"
    ],
    [
      "Veg Fried Rice",
      "Classic fried rice with scallions",
      230,
      "Rice",
      "veg"
    ],
    [
      "Kung Pao Chicken",
      "Dried chillies, peanuts and wok-tossed chicken",
      330,
      "Main Course",
      "non-veg"
    ],
    [
      "Schezwan Noodles",
      "Spicy schezwan noodles with veggies",
      280,
      "Noodles",
      "veg"
    ],
    [
      "Spring Rolls",
      "Crispy rolls with glass noodles and vegetables",
      220,
      "Starters",
      "veg"
    ],
    [
      "Chicken Wonton Soup",
      "Delicate dumplings in clear broth",
      240,
      "Soup",
      "non-veg"
    ],
    [
      "Manchow Soup",
      "Hot and tangy Indo-Chinese soup",
      180,
      "Soup",
      "veg"
    ],
    [
      "Mango Pudding",
      "Silky chilled mango dessert",
      140,
      "Desserts",
      "veg"
    ]
  ],
  "Burgers": [
    [
      "Classic Cheese Burger",
      "Patties, melted cheddar and special sauce",
      220,
      "Burgers",
      "non-veg"
    ],
    [
      "Crispy Chicken Burger",
      "Fried chicken, slaw and sriracha mayo",
      240,
      "Burgers",
      "non-veg"
    ],
    [
      "Veggie Burger",
      "Grilled veggie patty, cheese and greens",
      190,
      "Burgers",
      "veg"
    ],
    [
      "Paneer Burger",
      "Crispy paneer patty with mint mayo",
      210,
      "Burgers",
      "veg"
    ],
    [
      "Loaded Fries",
      "Fries with cheese sauce and herbs",
      150,
      "Sides",
      "veg"
    ],
    [
      "Chicken Nuggets",
      "Golden crumbed chicken bites",
      180,
      "Sides",
      "non-veg"
    ],
    [
      "Peri Peri Fries",
      "Fries dusted with peri peri spice",
      160,
      "Sides",
      "veg"
    ],
    [
      "Cold Coffee",
      "Frothy chilled coffee",
      140,
      "Beverages",
      "veg"
    ],
    [
      "Chocolate Thick Shake",
      "Blended thick chocolate shake",
      190,
      "Beverages",
      "veg"
    ]
  ],
  "Pizza": [
    [
      "Margherita Pizza",
      "Classic tomato, mozzarella and basil",
      320,
      "Pizza",
      "veg"
    ],
    [
      "Farmhouse Pizza",
      "Bell peppers, onion, corn and mushroom",
      380,
      "Pizza",
      "veg"
    ],
    [
      "Pepperoni Pizza",
      "Loaded with pepperoni and extra cheese",
      420,
      "Pizza",
      "non-veg"
    ],
    [
      "BBQ Chicken Pizza",
      "Smoky BBQ chicken with red onions",
      400,
      "Pizza",
      "non-veg"
    ],
    [
      "Paneer Tikka Pizza",
      "Tandoori paneer on a spiced base",
      390,
      "Pizza",
      "veg"
    ],
    [
      "Garlic Breadsticks",
      "Oven-baked sticks brushed with garlic butter",
      180,
      "Sides",
      "veg"
    ],
    [
      "Cheesy Nachos",
      "Crisp nachos with cheese sauce",
      190,
      "Sides",
      "veg"
    ],
    [
      "Chocolate Lava Cake",
      "Molten-center chocolate cake",
      160,
      "Desserts",
      "veg"
    ]
  ],
  "Fast Food": [
    [
      "Masala Maggi",
      "Street-style masala noodles",
      90,
      "Main Course",
      "veg"
    ],
    [
      "Vada Pav",
      "Mumbai's favorite spiced potato fritter bun",
      50,
      "Snacks",
      "veg"
    ],
    [
      "Pav Bhaji",
      "Buttery mashed vegetables with soft pav",
      180,
      "Main Course",
      "veg"
    ],
    [
      "Frankie Roll",
      "Wrapped paratha with spiced filling",
      150,
      "Snacks",
      "veg"
    ],
    [
      "Chicken Frankie",
      "Chicken tikka wrapped in paratha",
      190,
      "Snacks",
      "non-veg"
    ],
    [
      "French Fries",
      "Crispy golden fries",
      120,
      "Sides",
      "veg"
    ],
    [
      "Pani Puri",
      "Crisp shells with spiced potato and tangy water",
      80,
      "Chats",
      "veg"
    ],
    [
      "Cold Coffee",
      "Frothy chilled coffee",
      130,
      "Beverages",
      "veg"
    ]
  ],
  "Desserts": [
    [
      "Belgian Chocolate Cake",
      "Rich, moist chocolate cake with ganache",
      180,
      "Cakes",
      "veg"
    ],
    [
      "Red Velvet Slice",
      "Classic with cream cheese frosting",
      230,
      "Cakes",
      "veg"
    ],
    [
      "New York Cheesecake",
      "Baked classic with berry compote",
      240,
      "Desserts",
      "veg"
    ],
    [
      "Brownie Sundae",
      "Warm brownie with vanilla ice cream",
      220,
      "Desserts",
      "veg"
    ],
    [
      "Blueberry Muffin",
      "Bursting with wild blueberries",
      110,
      "Bakery",
      "veg"
    ],
    [
      "Butter Croissant",
      "Flaky laminated French classic",
      130,
      "Bakery",
      "veg"
    ],
    [
      "Choc Chip Cookies",
      "Chewy cookies with dark chocolate",
      120,
      "Bakery",
      "veg"
    ],
    [
      "Mango Mousse Cup",
      "Alphonso mango mousse",
      170,
      "Desserts",
      "veg"
    ],
    [
      "Tiramisu",
      "Espresso-soaked layers with mascarpone",
      240,
      "Desserts",
      "veg"
    ],
    [
      "Gulab Jamun",
      "Warm milk dumplings in sugar syrup",
      110,
      "Desserts",
      "veg"
    ]
  ],
  "Bakery": [
    [
      "Blueberry Muffin",
      "Bursting with wild blueberries",
      110,
      "Bakery",
      "veg"
    ],
    [
      "Double Choc Muffin",
      "Dark chocolate studded crumb",
      120,
      "Bakery",
      "veg"
    ],
    [
      "Butter Croissant",
      "Flaky laminated French classic",
      130,
      "Bakery",
      "veg"
    ],
    [
      "Cinnamon Roll",
      "Swirled brioche with cream cheese glaze",
      160,
      "Bakery",
      "veg"
    ],
    [
      "Banana Walnut Loaf",
      "Melted banana loaf with toasted walnuts",
      140,
      "Bakery",
      "veg"
    ],
    [
      "Chocolate Éclair",
      "Choux pastry with chocolate ganache",
      210,
      "Bakery",
      "veg"
    ],
    [
      "Artisan Sourdough",
      "Wild-fermented crusty loaf",
      180,
      "Bakery",
      "veg"
    ],
    [
      "Vanilla Bean Tart",
      "Silky custard in a buttery shell",
      200,
      "Desserts",
      "veg"
    ]
  ],
  "Healthy": [
    [
      "Quinoa Buddha Bowl",
      "Quinoa, roasted veggies and avocado",
      320,
      "Bowls",
      "vegan"
    ],
    [
      "Greek Salad",
      "Cucumber, tomato, feta and olives",
      260,
      "Salads",
      "veg"
    ],
    [
      "Kale Caesar",
      "Massaged kale with cashew dressing",
      280,
      "Salads",
      "vegan"
    ],
    [
      "Avocado Toast",
      "Sourdough with smashed avocado",
      240,
      "Toasts",
      "vegan"
    ],
    [
      "Cold Pressed Detox",
      "5-ingredient cold-pressed juice",
      160,
      "Beverages",
      "vegan"
    ],
    [
      "Grilled Chicken Bowl",
      "Lemongrass chicken over brown rice",
      340,
      "Bowls",
      "non-veg"
    ],
    [
      "Paneer Salad Platter",
      "Grilled paneer over garden leaves",
      260,
      "Salads",
      "veg"
    ],
    [
      "Protein Smoothie Bowl",
      "Plant protein, berries and coconut",
      290,
      "Bowls",
      "vegan"
    ],
    [
      "Iced Hibiscus Tea",
      "House-infused, lightly sweetened",
      90,
      "Beverages",
      "vegan"
    ]
  ],
  "Seafood": [
    [
      "Meen Pollichathu",
      "Banana leaf-wrapped spiced fish",
      380,
      "Main Course",
      "non-veg"
    ],
    [
      "Prawn Ghee Roast",
      "Butter-roasted prawns with spices",
      420,
      "Main Course",
      "non-veg"
    ],
    [
      "Chilli Garlic Prawns",
      "Juicy prawns in sticky chilli garlic glaze",
      400,
      "Starters",
      "non-veg"
    ],
    [
      "Fish Curry with Rice",
      "Tangy coastal fish curry",
      300,
      "Main Course",
      "non-veg"
    ],
    [
      "Crab Pepper Fry",
      "Cracked crab roasted with pepper",
      450,
      "Starters",
      "non-veg"
    ],
    [
      "Appam & Fish Molee",
      "Lacy appams with coconut fish stew",
      330,
      "Main Course",
      "non-veg"
    ],
    [
      "Kerala Fish Fry",
      "Crisp pan-fried pearl spot",
      280,
      "Starters",
      "non-veg"
    ]
  ],
  "Continental": [
    [
      "Grilled Chicken Steak",
      "Herb-butter chicken with mashed potatoes",
      420,
      "Main Course",
      "non-veg"
    ],
    [
      "Penne Alfredo",
      "Fettuccine tossed in creamy parmesan",
      380,
      "Pasta",
      "veg"
    ],
    [
      "Spaghetti Aglio Olio",
      "Garlic, chilli and olive oil",
      320,
      "Pasta",
      "vegan"
    ],
    [
      "Farmhouse Flatbread",
      "Wood-fired with seasonal toppings",
      360,
      "Pizza",
      "veg"
    ],
    [
      "Cream of Mushroom Soup",
      "Silky button mushroom soup",
      200,
      "Soup",
      "veg"
    ],
    [
      "Tiramisu",
      "Espresso-soaked layers with mascarpone",
      240,
      "Desserts",
      "veg"
    ]
  ],
  "Street Food": [
    [
      "Pav Bhaji",
      "Buttery mashed vegetables with soft pav",
      160,
      "Main Course",
      "veg"
    ],
    [
      "Vada Pav",
      "Mumbai's favorite spiced potato bun",
      50,
      "Snacks",
      "veg"
    ],
    [
      "Pani Puri",
      "Crisp shells with spiced potato and tangy water",
      70,
      "Chats",
      "veg"
    ],
    [
      "Bhel Puri",
      "Puffed rice with tamarind and sev",
      90,
      "Chats",
      "veg"
    ],
    [
      "Samosa Chaat",
      "Crisp samosa with chole and chutneys",
      120,
      "Chats",
      "veg"
    ],
    [
      "Kathi Roll",
      "Wrapped paratha with egg and veggies",
      130,
      "Snacks",
      "veg"
    ],
    [
      "Chicken Kathi Roll",
      "Chicken tikka wrapped in paratha",
      180,
      "Snacks",
      "non-veg"
    ],
    [
      "Ras Malai",
      "Soft cheese discs in saffron milk",
      140,
      "Desserts",
      "veg"
    ]
  ],
  "Maharashtrian": [
    [
      "Misal Pav",
      "Spicy sprouted lentils with crispy pav",
      160,
      "Main Course",
      "veg"
    ],
    [
      "Thalipeeth",
      "Multigrain savoury pancake with butter",
      150,
      "Tiffins",
      "veg"
    ],
    [
      "Sabudana Khichdi",
      "Tapioca pearls with peanuts and lemon",
      140,
      "Tiffins",
      "veg"
    ],
    [
      "Puran Poli",
      "Sweet stuffed flatbread with ghee",
      130,
      "Desserts",
      "veg"
    ],
    [
      "Kothimbir Vadi",
      "Coriander fritters, Maharashtrian-style",
      120,
      "Starters",
      "veg"
    ],
    [
      "Bhakri & Thecha",
      "Jowar roti with green chilli chutney",
      110,
      "Breads",
      "veg"
    ],
    [
      "Kolhapuri Chicken",
      "Earthy red-chilli chicken curry",
      330,
      "Main Course",
      "non-veg"
    ],
    [
      "Pandhra Rassa",
      "White coconut-peanut chicken curry",
      310,
      "Main Course",
      "non-veg"
    ]
  ]
};

const BANK_ORDER = [
  "Starters",
  "Soup",
  "Chats",
  "Snacks",
  "Tiffins",
  "Main Course",
  "Biryani",
  "Rice",
  "Noodles",
  "Pasta",
  "Pizza",
  "Burgers",
  "Bowls",
  "Salads",
  "Toasts",
  "Breads",
  "Sides",
  "Cakes",
  "Desserts",
  "Bakery",
  "Beverages"
];

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Build a deterministic 15-item menu for a restaurant from its cuisine list.
export function buildMenuForCuisines(restaurantId: string, cuisines: string[]): MenuItem[] {
  const rng = mulberry32(restaurantId.split("").reduce((acc, ch) => acc + ch.charCodeAt(0), 0));
  const rand = () => rng();
  const intBetween = (min: number, max: number) => min + Math.floor(rand() * (max - min + 1));
  const pickN = <T,>(arr: T[], n: number): T[] => {
    const copy = [...arr];
    const out: T[] = [];
    while (out.length < n && copy.length > 0) {
      out.push(copy.splice(Math.floor(rand() * copy.length), 1)[0]);
    }
    return out;
  };
  const usable = cuisines.filter((c) => MENU_BANKS[c]);
  if (usable.length === 0) usable.push("North Indian");
  const pool = new Map<string, MenuBankItem>();
  for (const cuisine of usable) {
    for (const item of MENU_BANKS[cuisine]) {
      if (!pool.has(item[0])) pool.set(item[0], item);
    }
  }
  const items = [...pool.values()];
  const count = intBetween(15, 20);
  const chosen = pickN(items, Math.min(count, items.length)).sort(
    (a, b) => BANK_ORDER.indexOf(a[3]) - BANK_ORDER.indexOf(b[3])
  );
  const bestsellers = ["Butter Chicken", "Masala Dosa", "Hyderabadi Chicken Biryani", "Margherita Pizza", "Chettinad Chicken", "Quinoa Buddha Bowl", "Classic Cheese Burger", "Vada Pav"];
  return chosen.map(([name, description, price, category, vegType], i) => {
    const isBestseller = bestsellers.includes(name) || rand() < 0.18;
    return {
      id: `m${restaurantId.replace(/[^0-9]/g, "")}0${i}_${restaurantId}`,
      restaurantId,
      name,
      description,
      price,
      vegType,
      category,
      isBestseller,
      isAvailable: rand() < 0.97,
      rating: isBestseller ? Math.round((4.2 + rand() * 0.6) * 10) / 10 : undefined,
      ratingCount: isBestseller ? intBetween(150, 1200) : undefined,
      nutrition: {
        calories: intBetween(120, 900),
        allergens: rand() < 0.7 ? ["Dairy", "Gluten", "Soy", "Peanuts"].slice(0, intBetween(1, 2)) : [],
      },
    };
  });
}
